# Generated by Django 4.2.3 on 2023-07-26 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('new_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=16)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_logs', to='accounts.account')),
                ('curency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_logs', to='accounts.currency')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
